// eslint-disable-next-line import/prefer-default-export
export const voices = {
  Zeina: { voice: 'Zeina', language: 'Arabic (arb)' },
  'Arlet-Neural': { voice: 'Arlet-Neural', language: 'Catalan (ca-ES)' },
  Gwyneth: { voice: 'Gwyneth', language: 'Welsh (cy-GB)' },
  Naja: { voice: 'Naja', language: 'Danish (da-DK)' },
  'Hannah-Neural': { voice: 'Hannah-Neural', language: 'German (Austrian) (de-AT)' },
  Marlene: { voice: 'Marlene', language: 'German (de-DE)' },
  Salli: { voice: 'Salli', language: 'English (US) (en-US)' },
  Nicole: { voice: 'Nicole', language: 'English (Australian) (en-AU)' },
  Amy: { voice: 'Amy', language: 'English (British) (en-GB)' },
  Geraint: { voice: 'Geraint', language: 'English (Welsh) (en-GB-WLS)' },
  Aditi: { voice: 'Aditi', language: 'Hindi (hi-IN)' },
  'Aria-Neural': { voice: 'Aria-Neural', language: 'English (New Zealand) (en-NZ)' },
  'Ayanda-Neural': {
    voice: 'Ayanda-Neural',
    language: 'English (South Africa) (en-ZA)',
  },
  Conchita: { voice: 'Conchita', language: 'Spanish (Castilian) (es-ES)' },
  Mia: { voice: 'Mia', language: 'Spanish (Mexico) (es-MX)' },
  Penelope: { voice: 'Penelope', language: 'Spanish (Latin American) (es-US)' },
  Chantal: { voice: 'Chantal', language: 'French (Canadian) (fr-CA)' },
  Celine: { voice: 'Celine', language: 'French (fr-FR)' },
  Dora: { voice: 'Dora', language: 'Icelandic (is-IS)' },
  Carla: { voice: 'Carla', language: 'Italian (it-IT)' },
  Mizuki: { voice: 'Mizuki', language: 'Japanese (ja-JP)' },
  Seoyeon: { voice: 'Seoyeon', language: 'Korean (ko-KR)' },
  Liv: { voice: 'Liv', language: 'Norwegian (nb-NO)' },
  Lotte: { voice: 'Lotte', language: 'Dutch (nl-NL)' },
  Ewa: { voice: 'Ewa', language: 'Polish (pl-PL)' },
  Vitoria: { voice: 'Vitoria', language: 'Portuguese (Brazilian) (pt-BR)' },
  Ines: { voice: 'Ines', language: 'Portuguese (European) (pt-PT)' },
  Carmen: { voice: 'Carmen', language: 'Romanian (ro-RO)' },
  Tatyana: { voice: 'Tatyana', language: 'Russian (ru-RU)' },
  Astrid: { voice: 'Astrid', language: 'Swedish (sv-SE)' },
  Filiz: { voice: 'Filiz', language: 'Turkish (tr-TR)' },
  Zhiyu: { voice: 'Zhiyu', language: 'Chinese (Mandarin) (zh-CN)' },
};
